version: '3'

services:
    db:
        build: db
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - lsnet
    php:
        build: php7.1-fpm
        expose:
            - "9000"
            - "80"
        depends_on:
            - db
        volumes:
            - C:\Users\chris\Projects\legacyshield2\legacyshield:/var/www/symfony
            - C:\Users\chris\Projects\legacyshield2\docker-symfony\logs\symfony:/var/www/symfony/app/logs
            - ./var:/var
        networks:
            - lsnet
    node:
        build: node
        volumes:
            - C:\Users\chris\Projects\legacyshield2\legacyshield:/var/www/symfony
        networks:
            - lsnet
    nginx:
        build: nginx
        depends_on:
            - php
            - mailhog
        ports:
            - "80:80"
        volumes:
            - C:\Users\chris\Projects\legacyshield2\legacyshield:/var/www/symfony
            - C:\Users\chris\Projects\legacyshield2\docker-symfony\logs\nginx:/var/log/nginx
        networks:
            - lsnet
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - ./var:/var
        networks:
            - lsnet


    auditdb:
        build: auditdb
        volumes:
            - ./.data/auditdb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${AUDIT_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${AUDIT_MYSQL_DATABASE}
            MYSQL_USER: ${AUDIT_MYSQL_USER}
            MYSQL_PASSWORD: ${AUDIT_MYSQL_PASSWORD}
        networks:
            - auditnet
    auditphp:
        build: auditphp7.1-fpm
        depends_on:
            - auditdb
        volumes:
            - C:\Users\chris\Projects\legacyshield2\legacyshieldaudit:/var/www/symfony
            - C:\Users\chris\Projects\legacyshield2\docker-symfony\logs\auditphp:/var/www/symfony/app/logs
        networks:
            - auditnet
    auditnginx:
        build: auditnginx
        depends_on:
            - auditphp
        volumes:
            - C:\Users\chris\Projects\legacyshield2\legacyshieldaudit:/var/www/symfony
            - C:\Users\chris\Projects\legacyshield2\docker-symfony\logs\auditnginx:/var/log/nginx
        networks:
            - auditnet
networks:
    lsnet:
    auditnet: