version: '3'

services:
    db:
        build: db
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7.1-fpm
        depends_on:
            - db
        ports:
            - "9000:9000"
        volumes:
            - symfony-bind-mount:/var/www/symfony
            - symfony-logs-bind-mount:/var/www/symfony/app/logs
            - mailhog-storage:/var
    node:
        build: node
        volumes:
            - symfony-bind-mount:/var/www/symfony
    nginx:
        build: nginx
        depends_on:
            - php
            - mailhog
        ports:
            - "80:80"
        volumes:
            - symfony-bind-mount:/var/www/symfony
            - nginx-logs-bind-mount:/var/log/nginx
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        volumes:
            - symfony-bind-mount:/var/www/symfony
            - symfony-logs-bind-mount:/var/www/symfony/app/logs
            - mailhog-storage:/var
volumes:
    symfony-bind-mount:
        driver: local
        driver_opts:
            o: bind,rw
            type: none
            device: ${SYMFONY_APP_PATH}
    nginx-logs-bind-mount:
        driver: local
        driver_opts:
            o: bind,rw
            type: none
            device: ${DOCKER_SYMFONY_PATH}/logs/nginx
    symfony-logs-bind-mount:
        driver: local
        driver_opts:
            o: bind,rw
            type: none
            device: ${DOCKER_SYMFONY_PATH}/logs/symfony
    mailhog-storage:
        driver: local
        driver_opts:
            o: bind,rw
            type: none
            device: ${DOCKER_SYMFONY_PATH}/doc
